prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/new_in_20_2.sql
@@application/shared_components/navigation/lists/stack_grouping.sql
@@application/shared_components/navigation/lists/declarative_font_formatting.sql
@@application/shared_components/navigation/lists/chart_links.sql
@@application/shared_components/navigation/lists/sorting.sql
@@application/shared_components/navigation/lists/styling_tooltip_labels.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar_top.sql
@@application/shared_components/navigation/lists/administration.sql
@@application/shared_components/navigation/lists/charts.sql
@@application/shared_components/navigation/lists/reference_js.sql
@@application/shared_components/navigation/lists/js_customizations.sql
@@application/shared_components/navigation/lists/das.sql
@@application/shared_components/navigation/lists/series_color.sql
@@application/shared_components/navigation/lists/y2_axis.sql
@@application/shared_components/navigation/lists/jet_plug_in_components.sql
@@application/shared_components/navigation/lists/time_axis.sql
@@application/shared_components/navigation/lists/zoom_scroll.sql
@@application/shared_components/navigation/lists/styling_data_labels.sql
@@application/shared_components/navigation/lists/formatting_values.sql
@@application/shared_components/navigation/lists/3d_effect.sql
@@application/shared_components/navigation/lists/data_densify.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/box_plot_explained_gif.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/legend_acme_png.sql
@@application/shared_components/files/legend_deli_png.sql
@@application/shared_components/files/legend_shop_png.sql
@@application/shared_components/files/legend_store_png.sql
@@application/plugin_settings.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/trim_all_page_items.sql
@@application/shared_components/logic/application_items/last_view.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/projects.sql
@@application/shared_components/user_interface/lovs/salary_amounts.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/region/div_region_with_id.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/security/authentications/apex_auth.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_translated_message.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_display_source.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_html5_bar_chart.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_sampleappfooter.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_badge_list.sql
@@application/shared_components/plugins/region_type/com_apex_legend_jet.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00039.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00045.sql
@@application/pages/page_00046.sql
@@application/pages/page_00047.sql
@@application/pages/page_00048.sql
@@application/pages/page_00049.sql
@@application/pages/page_00101.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_set_plscope_settings.sql
@@application/deployment/install/install_tables.sql
@@application/deployment/install/install_triggers.sql
@@application/deployment/install/install_sample_data.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
