ALTER TABLE "RDI_FRAME_PERIOD" ADD CONSTRAINT "FK_FRAME_PERIOD" FOREIGN KEY ("PERIOD_ID")
	  REFERENCES "RDI_PERIOD" ("PERIOD_ID") ON DELETE CASCADE ENABLE;
/  
ALTER TABLE "RDI_FRAME_PERIOD" ADD CONSTRAINT "FK_PERIOD_FRAME" FOREIGN KEY ("FRAME_ID")
	  REFERENCES "RDI_FRAME" ("FRAME_ID") ON DELETE CASCADE ENABLE;
/
 
	  	  